logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org.springframework: info
    xyz.zhiweicoding: debug

server:
  port: 8082

spring:
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: elebike
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  config:
    activate:
      on-profile:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cos:
  secretId:
  secretKey:
  region:
  bucket:
  baseUrl:

management:
  health:
    elasticsearch:
      enabled: false